# Generated by Django 3.1.4 on 2020-12-24 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='money',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='貸したお金'),
        ),
    ]
